
export const TYPES = {
    IUserAuthController: Symbol.for("IUserAuthController"),
    UserAuthController: Symbol.for("UserAuthController"),
    IAdminAuthController: Symbol.for("IAdminAuthController"),
    AdminAuthController: Symbol.for("AdminAuthController"),
    IUserAuthService: Symbol.for("IUserAuthService"),
    UserAuthService: Symbol.for("UserAuthService"),
    IAdminAuthService: Symbol.for("IAdminAuthService"),
    AdminAuthService: Symbol.for("AdminAuthService"),
    IUserRepository: Symbol.for("IUserRepository"),
    UserRepository: Symbol.for("UserRepository"),
    IAdminRepository: Symbol.for("IAdminRepository"),
    AdminRepository: Symbol.for("AdminRepository"),
    IOtpService: Symbol.for("IOtpService"),
    OtpService: Symbol.for("OtpService"),
    IOAuthClient: Symbol.for("IOAuthClient"),
    OAuthClient: Symbol.for("OAuthClient"),
    IEmailService: Symbol.for("IEmailService"),
    EmailService: Symbol.for("EmailService"),
    IJwtService: Symbol.for("IJwtService"),
    JwtService: Symbol.for("JwtService"),
    IOtpRepository: Symbol.for("IOtpRepository"),
    OtpRepository: Symbol.for("OtpRepository"),
    IMailService: Symbol.for("IMailService"),
    MailService: Symbol.for("MailService"),
    IRedisClient: Symbol.for("IRedisClient"),
    ICommunityAdminAuthController: Symbol.for("ICommunityAdminAuthController"),
    CommunityAdminAuthController: Symbol.for("CommunityAdminAuthController"),
    ICommunityAdminAuthService: Symbol.for("ICommunityAdminAuthService"),
    CommunityAdminAuthService: Symbol.for("CommunityAdminAuthService"),
    ICommunityAdminRepository: Symbol.for("ICommunityAdminRepository"),
    CommunityAdminRepository: Symbol.for("CommunityAdminRepository"),
    ICommunityRequestRepository: Symbol.for("ICommunityRequestRepository"),
    UserProfileController: Symbol.for("UserProfileController"),
    IUserProfileController: Symbol.for("IUserProfileController"),
    IUserService: Symbol.for("IUserService"),
    UserService: Symbol.for("UserService"),
    WalletController: Symbol.for("WalletController"),
    IWalletController: Symbol.for("IWalletController"),
    IWalletService: Symbol.for("IWalletService"),
    WalletService: Symbol.for("WalletService"),
    IWalletRepository: Symbol.for("IWalletRepository"),
    WalletRepository: Symbol.for("WalletRepository"),

    ReferralHistoryRepository: Symbol.for("ReferralHistoryRepository"),
    IReferralHistoryRepository: Symbol.for("IReferralHistoryRepository"),
    IPointsHistoryRepository: Symbol.for("IPointsHistoryRepository"),
    PointsHistoryRepository: Symbol.for("PointsHistoryRepository"),
    IDailyCheckInRepository: Symbol.for("IDailyCheckInRepository"),
    DailyCheckInRepository: Symbol.for("DailyCheckInRepository"),
    IReferralService: Symbol.for("IReferralService"),
    ReferralService: Symbol.for("ReferralService"),
    IPointsService: Symbol.for("IPointsService"),
    PointsService: Symbol.for("PointsService"),
    IReferralController: Symbol.for("IReferralController"),
    ReferralController: Symbol.for("ReferralController"),
    IPointsController: Symbol.for("IPointsController"),
    PointsController: Symbol.for("PointsController"),

    
    



}

